# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(to='album.Category'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Image'),
        ),
    ]
